name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Add additional steps for building/testing if necessary

    - name: Deploy to Hostinger
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        REMOTE_HOST: ${{ secrets.IP }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: ${{ secrets.PORT }}
        SOURCE: "./"
        TARGET: "kost-skripsi" # Replace with your actual target path on Hostinger
        ARGS: "-avzr --delete"
